language: generic
install:
  - gem uninstall bundler
  - gem install bundler --version '1.7.4'
script: "rake"

sudo: required
services:
    - docker

before_install:
    - gem install bundler --pre
    - docker build -t prudhvibharadwaj/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true prudhvibharadwaj/docker-react npm run test